services:
  db:
    image: postgres:16-alpine
    container_name: vehicle_api_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - vehicle_db_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${LOCAL_DB_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - vehicle_api_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: vehicle_api_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USER}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:${LOCAL_PGADMIN_PORT}"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - vehicle_api_network

networks:
  vehicle_api_network:
    driver: bridge

volumes:
  vehicle_db_data:
